<a href="https://colab.research.google.com/github/221230003-coder/221230003-pengantar-ML/blob/main/221230003_Pengantar_ML_week_02_latihan_praktikum4_list_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.maximum(torch.tensor(0.0), tensor)

activated = relu_activation(output)

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, eps=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)
    std = tensor.std(dim=0, unbiased=False, keepdim=True)
    return (tensor - mean) / (std + eps)

normalized = simple_batch_norm(X)

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

# ✅ Assertions
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"

# === CETAK HASIL ===
print("✅ Linear layer output (first 5 rows):\n", output[:5])
print("\n✅ ReLU activated output (first 5 rows):\n", activated[:5])
print("\n✅ Batch normalized X (first 5 rows):\n", normalized[:5])
print("\n✅ One-hot encoded labels:\n", one_hot)

### BONUS: ADVANCED TENSOR OPERATIONS ###
def manual_matrix_multiply(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    result = torch.zeros(rows_A, cols_B)
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("\n✅ Manual matrix multiplication result:\n", manual_result)
print("\n✅ Torch.matmul result:\n", torch_result)
print("✅ Semua operasi PyTorch berhasil dijalankan")


✅ Linear layer output (first 5 rows):
 tensor([[ 2.6718],
        [-1.5847],
        [ 0.3128],
        [-3.3263],
        [-0.8955]])

✅ ReLU activated output (first 5 rows):
 tensor([[2.6718],
        [0.0000],
        [0.3128],
        [0.0000],
        [0.0000]])

✅ Batch normalized X (first 5 rows):
 tensor([[ 0.6221,  0.3032,  0.0686,  0.4586,  1.0745, -0.3614,  1.8699,  0.1732,
         -1.6632,  0.6986],
        [ 0.1064,  0.4986, -0.0759, -0.1752,  1.6651, -0.9423,  1.6984, -1.5373,
          2.0250,  0.4460],
        [-0.5217,  0.1390,  1.0684, -1.6947,  1.4526, -1.4214, -0.9763, -0.2059,
          1.0627, -1.2268],
        [-1.3924,  1.6212, -1.1213,  2.1118, -0.8727,  0.0708, -0.0924, -0.4911,
          0.9381,  0.8000],
        [ 0.3211,  1.9201, -1.4037, -0.8061, -1.5591,  0.0146,  0.0959,  1.6470,
          0.3071, -0.3647]])

✅ One-hot encoded labels:
 tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [